//console.log(true || false);
//console.log(true || true);
//console.log(true && false);
//console.log(true && true);
//console.log(!true);
//console.log(!false);
//console.log(true === false);
//console.log(4 == "4");
//console.log(4 === "4");
//console.log(!"4");
//console.log(!"");
//console.log(!!"4");
//console.log(!!"");
